import Header from "@/components/Header";
import "@/styles/globals.css";

export const metadata = {
  title: "Rasadent",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
